### ISSUE TITLE
[PRESENTATION] Intro to Subjects! - Michael Madsen

### ISSUE THREAD

**Issue by mgm87** [AngularJSUtah/meetups-slc-group#19]
I have a presentation on subjects. What they are and how to use them. 
I cover a little bit of material from https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93 but with angular syntax. As well as a deeper dive into the differences between different Subjects and their applications.

**Comment by waltercodes** [comment]
Thanks so much for presenting on this! You helped us get a strong start in our new location.
