### ISSUE TITLE
What's up with Angular v4.0? Proposed Presentation

### ISSUE THREAD

**Issue by kdparkinson** [AngularJSUtah/meetups-slc-group#5]
I will study up on the new changes in the latest release of Angular (4.0) and present on the changes and share what I understand and or learned from the [release notes](https://github.com/angular/angular/blob/master/CHANGELOG.md). I may also attempt to cover Angular CLI a pretty sweet tool. https://cli.angular.io/

**Comment by waltercodes** [comment]
:+1:

**Comment by waltercodes** [comment]
Thanks for presenting!
